theme: jekyll-theme-minimal

title: open-source.world
description: The World of Open-Source

logo: https://upload.wikimedia.org/wikipedia/commons/5/51/Icon_DINA_Voraussetzungen_Digitale_Nachhaltigkeit_04_Verteilte_Standorte_Farbig.svg
